# Generated by Django 5.2.8 on 2026-02-06 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('PORSCHE', 'Porsche'), ('FERRARI', 'Ferrari'), ('FORD', 'Ford'), ('LAMBORGHINI', 'Lamborghini'), ('TESLA', 'Tesla'), ('BUGATTI', ' Bugatti')], help_text='Marca do carro', max_length=20, validators=[django.core.validators.MinLengthValidator(4, 'Mínimo de 4 caracteres')], verbose_name='Marca')),
                ('modelo', models.CharField(default=0, help_text='Modelo do carro', max_length=20, validators=[django.core.validators.MinLengthValidator(2, 'Mínimo de 2 caracteres')], verbose_name='Modelo')),
                ('ano', models.IntegerField(default=2026, help_text='Digite o ano do carro', verbose_name='Ano')),
                ('alugado', models.BooleanField(default='False', help_text='Marque se o carro está alugado', verbose_name='Alugado?')),
                ('placa', models.CharField(default=0, help_text='Digite a placa do carro', max_length=7, validators=[django.core.validators.MinLengthValidator(7, 'Mínimo 7 caracteres')], verbose_name='Placa')),
                ('valor_diaria', models.DecimalField(decimal_places=2, default=0, help_text='Calculado automáticamente', max_digits=8, validators=[django.core.validators.MinValueValidator(200)], verbose_name='Valor da diária')),
                ('seguro', models.DecimalField(decimal_places=2, default=0, help_text='Valor do seguro do carro selecionado', max_digits=8, validators=[django.core.validators.MinValueValidator(50, 'Valor mínimo é 50')], verbose_name='Seguro')),
                ('ultima_revisao', models.DateField(help_text='Data da última revisão', verbose_name='Data da última revisão')),
                ('ipva', models.BooleanField(default=True, help_text='O IPVA está pago?', verbose_name='IPVA')),
            ],
            options={
                'verbose_name': 'CARRO',
                'verbose_name_plural': 'CARROS',
                'abstract': False,
            },
        ),
    ]
