# Generated by Django 5.2.8 on 2026-02-08 11:51

import django.core.validators
import django.db.models.deletion
import locadora_app.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='alugado',
            field=models.BooleanField(default='False', help_text='Marque se quer alugar', verbose_name='Alugar?'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='ano',
            field=models.IntegerField(default=2026, help_text='Digite o ano do carro', validators=[locadora_app.validators.validators.validar_ano], verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='seguro',
            field=models.DecimalField(decimal_places=2, default=None, editable=False, help_text='Valor do seguro do carro selecionado', max_digits=8, validators=[django.core.validators.MinValueValidator(50, 'Valor mínimo é 50')], verbose_name='Seguro'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='valor_diaria',
            field=models.DecimalField(decimal_places=2, default=None, editable=False, help_text='Calculado automáticamente', max_digits=8, validators=[django.core.validators.MinValueValidator(200)], verbose_name='Valor da diária'),
        ),
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(help_text='Qual foi a data de aluguel?', verbose_name='Data de início')),
                ('data_prevista_devolucao', models.DateField(help_text='Data prevista para devolução', verbose_name='Qual a data prevista para a devolução?')),
                ('data_devulucao', models.DateField(help_text='Data que o carro foi devolvido', null=True, verbose_name='Data de devolução')),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Valores finais', max_digits=8, verbose_name='Valor total')),
                ('ativo', models.BooleanField(default=True, help_text='Alugar carro?', verbose_name='Alugar carro?')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora_app.carro')),
            ],
            options={
                'verbose_name': ('ALUGUEL',),
                'verbose_name_plural': 'ALUGUEL',
            },
        ),
    ]
