# Generated by Django 5.2.8 on 2026-02-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora_app', '0002_alter_carro_alugado_alter_carro_ano_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluguel',
            name='data_devulucao',
        ),
        migrations.AddField(
            model_name='aluguel',
            name='data_devolucao',
            field=models.DateField(blank=True, help_text='Data que o carro foi devolvido', null=True, verbose_name='Data de devolução'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='alugado',
            field=models.BooleanField(default=False, help_text='Marque se o carro estiver alugado', verbose_name='Alugado?'),
        ),
    ]
