# Generated by Django 5.2.8 on 2026-02-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora_app', '0003_remove_aluguel_data_devulucao_aluguel_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Valores finais', max_digits=8, null=True, verbose_name='Valor total'),
        ),
    ]
